export const seoData = {
  "qr-generator": {
    title: "Free QR Code Generator – Create Custom QR Codes Online",
    description: "Generate QR codes for URLs, text, WiFi, email, and vCard instantly. Convert links to QR code easily. Download high-quality PNG or SVG. Free, unlimited, no signup required.",
    keywords: [
      "qr code generator",
      "free qr code generator",
      "create qr code online",
      "custom qr code maker",
      "generate qr code free",
      "qr code maker",
      "wifi qr code generator",
      "qr code generator no signup",
      "online qr code creator",
      "qr code for url",
      "qr converter",
      "convert to qr code",
      "qr code converter",
    ],
    canonical: "/qr-generator",
  },

  "password-gen": {
    title: "Password Generator – Create Strong Secure Passwords Free",
    description: "Generate strong, secure random passwords instantly. Customize length, symbols, numbers, and uppercase letters. Free military password generator, no signup, copy in one click.",
    keywords: [
      "password generator",
      "strong password generator",
      "secure password maker",
      "random password generator",
      "free password generator",
      "password generator online",
      "strong password creator",
      "complex password generator",
      "password generator no signup",
      "generate secure password",
      "military password generator",
    ],
    canonical: "/password-gen",
  },

  "unit-converter": {
    title: "Unit Converter – Convert Length, Weight, Temperature Free",
    description: "Free online unit converter for length, weight, temperature, area, speed, and volume. Fast, accurate unit conversion tool instantly. No signup required.",
    keywords: [
      "unit converter",
      "convert units online",
      "length converter",
      "weight converter",
      "temperature converter",
      "free unit converter",
      "metric to imperial converter",
      "kg to lbs converter",
      "cm to inches converter",
      "celsius to fahrenheit converter",
      "convertunits",
    ],
    canonical: "/unit-converter",
  },

  "youtube-thumbnail": {
    title: "YouTube Thumbnail Downloader – Download HD Thumbnails Free",
    description: "Download YouTube video thumbnails in the highest quality available (up to 1280x720 HD). Paste the video link into our youtube to thumbnail converter and save the image. Free, no signup.",
    keywords: [
      "youtube thumbnail downloader",
      "youtube thumbnail downloader online",
      "download youtube thumbnail",
      "yt thumbnail download",
      "youtube thumbnail hd",
      "youtube thumbnail downloader free",
      "download youtube video thumbnail",
      "youtube thumbnail download",
      "get youtube thumbnail",
      "youtube thumbnail extractor",
      "save youtube thumbnail",
      "online youtube thumbnail downloader",
      "youtube to thumbnail converter",
      "online thumbnail downloader",
    ],
    canonical: "/youtube-thumbnail",
  },

  "image-compressor": {
    title: "Image Compressor – Reduce Image Size Online Free",
    description: "Compress JPG, PNG, and WebP images online and cut file size while keeping them sharp. Free online image compression tool, fast, no signup, runs in your browser on mobile and desktop.",
    keywords: [
      "image compressor",
      "compress image online",
      "reduce image size",
      "jpg compressor",
      "png compressor",
      "compress image without losing quality",
      "image size reducer",
      "free image compressor",
      "compress photo online",
      "reduce photo size free",
      "image compression online",
      "online image compressor",
    ],
    canonical: "/image-compressor",
  },

  "image-to-text": {
    title: "Image to Text Converter – Extract Text from Image (OCR)",
    description: "Extract text from images using powerful OCR technology. Convert scanned photo to text online. Supports JPG, PNG, and scanned documents. Free, accurate, no signup required.",
    keywords: [
      "image to text",
      "ocr online",
      "extract text from image",
      "photo to text converter",
      "image to text converter free",
      "ocr image to text",
      "picture to text",
      "scan image to text",
      "free ocr tool",
      "convert image to text online",
      "ocr to text",
      "image ocr online",
      "photo to text convert online",
      "image to text converter online",
    ],
    canonical: "/image-to-text",
  },

  "signature-maker": {
    title: "Free Online Signature Maker – Convert Signature to Digital",
    description: "Create a free digital signature online: draw it, capture signature, or upload a photo of your paper/scanned signature to convert handwritten signature to digital transparent PNG. Free online signature converter, no signup.",
    keywords: [
      "free online signature",
      "online signature maker",
      "signature maker",
      "convert signature to digital",
      "signature converter",
      "scan signature online free",
      "digital signature online free",
      "create digital signature online",
      "handwritten signature to digital",
      "transparent signature png",
      "draw signature online",
      "signature maker no signup",
      "convert paper signature to digital",
      "convert scan signature into digital signature online free",
      "convert text to signature online",
      "electronic signature free no sign up",
      "digital signature creator free",
      "signature capture online",
      "e signature converter",
      "signature website free",
      "convert image to digital signature online free",
      "virtual signature free",
      "scanned signature online free",
      "convert signature",
      "online signature tool",
      "free online signatures",
      "make a signature online free",
      "make digital signature online free",
      "digital signature maker",
      "create signature online free",
      "convert signature on paper to digital",
      "signature type only online",
      "convert handwritten signature to digital",
      "e signature free online",
      "create digital signature image",
      "convert sign",
      "convert image to signature online free",
      "convert into signature",
      "digital signature converter",
      "e sign converter",
      "esign converter",
      "how to convert signature into digital signature",
      "how to get digital signature online free",
      "write signature online free",
      "online electronic signature free",
      "online signature free no sign up",
      "make electronic signature online free",
      "create digital signature online free no sign up",
      "adopt a signature free",
      "convert e signature",
      "image to signature converter free",
    ],
    canonical: "/signature-maker",
  },

  "heic-to-jpg": {
    title: "HEIC to JPG Converter – Convert iPhone Photos Free Online",
    description: "Convert iPhone HEIC photos to JPG instantly. Free, unlimited batch conversion, no signup, no watermark. Easily convert HEIC file to JPG on Windows, Android & any browser.",
    keywords: [
      "heic to jpg",
      "convert heic to jpg",
      "heic to jpg free",
      "iphone heic to jpg",
      "heic converter online",
      "convert heic to jpg online free",
      "heic to jpg unlimited",
      "free heic converter",
      "heic to jpeg",
      "convert iphone photos to jpg",
      "convert heic to jpg free unlimited",
      "online heic to jpg converter",
      "convert heic file to jpg",
      "free online convert heic to jpg",
      "how to quickly convert heic to jpg",
      "online tool to convert heic to jpg",
    ],
    canonical: "/heic-to-jpg",
  },

  "text-to-pdf": {
    title: "Text to PDF Converter – Convert TXT to PDF Online Free",
    description: "Convert plain text files into formatted PDF documents instantly. Customize font, margins, and layout. Free, no signup, download instantly.",
    keywords: [
      "text to pdf",
      "txt to pdf converter",
      "convert text to pdf",
      "text file to pdf",
      "text to pdf free",
      "online text to pdf converter",
      "notepad to pdf",
      "plain text to pdf",
      "txt to pdf online free",
      "convert txt file to pdf",
    ],
    canonical: "/text-to-pdf",
  },

  "image-converter": {
    title: "Image Converter – Convert JPG, PNG, WebP & Formats Online Free",
    description: "Convert images between JPG, PNG, WebP, and other formats instantly. Change image format or convert WebP to JPG in one click. Free, batch conversion supported.",
    keywords: [
      "image converter",
      "jpg to png",
      "png to jpg",
      "webp converter",
      "convert image format",
      "free image converter",
      "image format converter online",
      "jpg to webp converter",
      "png to webp",
      "convert image online free",
      "convert webp to jpg",
      "change image format",
      "image format converter",
      "image type converter",
      "file picture converter",
      "img online converter",
      "image file formats converter",
      "image conversion service",
      "graphic converter online",
      "image formats converter",
      "pic format converter",
      "photo file format converter",
    ],
    canonical: "/image-converter",
  },

  "image-resizer": {
    title: "Image Resizer – Resize Images & Pixels Online Free",
    description: "Resize images online by pixels, resolution, width, or height. Supports JPG, PNG, and WebP. Change photo resolution online with zero quality loss. Free, fast, no signup.",
    keywords: [
      "image resizer",
      "resize image online",
      "photo resizer",
      "change image size",
      "resize jpg png",
      "image resizer free",
      "resize image without losing quality",
      "resize photo online free",
      "image size changer",
      "resize image to specific size",
      "pixel converter online",
      "resolution converter",
      "photo resizer by pixels",
      "pixel size converter",
      "image pixel size converter",
      "change image pixels online",
      "convert photo resolution online",
      "change picture resolution online",
      "pixel size reducer",
      "pixel resize",
      "resize image converter",
      "convert jpg to px",
      "image converter pixels",
      "lower resolution converter",
      "pixels converter online",
      "photo pixel converter",
      "picture size converter pixels",
      "resize pixel image",
      "image size and resolution converter",
      "photo pixel size converter",
      "resize photo online pixels",
      "online image resolution converter",
      "pic resolution converter",
    ],
    canonical: "/image-resizer",
  },

  "image-cropper": {
    title: "Crop Image Online Free – Photo & Picture Cropper Tool",
    description: "Crop images and photos online for free. Freehand image cropper for JPG, PNG, or WebP. Crop to exact aspect ratio or custom size and download instantly. No signup required.",
    keywords: [
      "image cropper",
      "crop image online",
      "online image cropper",
      "photo cropper",
      "crop picture online",
      "crop photo online free",
      "image crop online",
      "free image cropper",
      "crop jpg png",
      "crop image without watermark",
      "freehand image cropper",
      "crop image online freehand",
      "aspect ratio cropper",
      "automatic image cropping",
      "online picture cropper",
      "crop photo online",
      "cropping online",
      "online cropping tool",
      "cropper online",
      "crop pictures online",
      "online crop tool",
      "cropped image online",
      "crop images online",
      "image ratio changer",
      "crop jpeg online",
      "online crop",
      "automatic crop image online",
      "crop photos free online",
      "jpg cropper",
      "online image ratio converter",
      "crop online jpg",
      "image cropping",
      "online crop image tool",
    ],
    canonical: "/image-cropper",
  },

  "word-counter": {
    title: "Word Counter Online – Count Words, Characters & Sentences",
    description: "Count words, characters, sentences, and paragraphs instantly with our free online word counter tool. Fast, accurate, and no signup required.",
    keywords: [
      "word counter",
      "character counter",
      "online word count tool",
      "count words online",
      "text counter tool",
      "word and character counter",
      "free word counter tool",
      "sentence counter",
      "paragraph counter",
      "online text analyzer",
    ],
    canonical: "/word-counter",
  },

  "case-converter": {
    title: "Case Converter – Uppercase, Lowercase & Title Case Tool",
    description: "Convert text to uppercase, lowercase, sentence case, or title case instantly. Free online case converter with one-click formatting.",
    keywords: [
      "case converter",
      "uppercase to lowercase",
      "lowercase to uppercase",
      "text case converter",
      "title case converter",
      "sentence case tool",
      "change text case online",
      "capitalize text tool",
      "free case converter",
      "text formatting tool",
    ],
    canonical: "/case-converter",
  },

  "base64-tool": {
    title: "Base64 Encoder & Decoder – Encode/Decode Online Free",
    description: "Encode and decode Base64 strings instantly with our free online tool. Supports text, images, and files. Convert hex to image online easily. Fast, accurate, and secure.",
    keywords: [
      "base64 encoder",
      "base64 decoder",
      "encode base64 online",
      "decode base64 string",
      "base64 converter tool",
      "base64 encode decode",
      "online base64 tool",
      "base64 image converter",
      "free base64 encoder",
      "base64 string decoder",
      "convert hex to image online",
    ],
    canonical: "/base64-tool",
  },

  "json-formatter": {
    title: "JSON Formatter & Validator – Beautify JSON Online Free",
    description: "Format, beautify, and validate JSON data instantly with our free JSON formatter tool. Fix errors and improve readability easily.",
    keywords: [
      "json formatter",
      "json beautifier",
      "json validator",
      "format json online",
      "pretty json tool",
      "json parser",
      "fix json errors",
      "online json viewer",
      "json editor tool",
      "free json formatter",
    ],
    canonical: "/json-formatter",
  },

  "lorem-ipsum": {
    title: "Lorem Ipsum Generator – Generate Dummy Text Online Free",
    description: "Generate Lorem Ipsum placeholder text instantly. Create paragraphs, sentences, or words for design and development projects.",
    keywords: [
      "lorem ipsum generator",
      "dummy text generator",
      "placeholder text generator",
      "lorem ipsum text",
      "generate lorem ipsum",
      "random text generator",
      "dummy content generator",
      "lorem ipsum paragraphs",
      "free lorem ipsum generator",
      "text filler generator",
    ],
    canonical: "/lorem-ipsum",
  },

  "color-picker": {
    title: "Color Picker Online – HEX, RGB, HSB & HSL Code Finder",
    description: "Free online color picker, hex code finder, and RGB color chooser. Pick any color and get its HEX, RGB, HSB, and HSL codes instantly with our hex to rgb converter. Made for designers & developers.",
    keywords: [
      "color picker",
      "hex color picker",
      "rgb color picker",
      "hsl color picker",
      "hex code finder",
      "color hex finder",
      "color code generator",
      "pick color online",
      "online color picker",
      "color palette tool",
      "rgb color picker online",
      "hsb color picker",
      "online color picker hex to rgb",
      "hexadecimal color picker",
      "rgb color finder",
      "color hex code picker",
      "rgb to hex color picker",
      "hue saturation lightness color picker",
      "8 digit hex color picker",
      "rgb picker",
      "rgb online",
      "rgb color chooser",
      "hex finder",
      "hex color online",
      "rgb colors picker",
      "color hex code finder",
      "rgb color online",
      "rgb colors online",
      "hexadecimal color selector",
      "hexadecimal color code picker",
      "hex color chooser",
      "rgb color matcher",
      "rgb colors selector",
      "hexadecimal colors picker",
      "hex color tool",
      "color selector rgb",
      "hex colors picker",
      "rgb color codes generator",
      "rgb color tool",
      "color hexadecimal online",
      "hex codes color picker",
      "hexcode color picker",
      "hex color reader",
      "rgb selector",
      "rgb lookup",
      "hex color generator",
      "színkód generátor",
      "color code from rgb",
    ],
    canonical: "/color-picker",
  },

  "add-watermark": {
    title: "Add Watermark to Image – Text & Logo Watermark Free",
    description: "Add text or logo watermark to any image online for free. Control position, opacity, size, and rotation. No signup, 100% browser-based.",
    keywords: [
      "add watermark to image",
      "watermark tool online",
      "image watermark generator",
      "add text watermark",
      "photo watermark online",
      "protect images watermark",
      "watermark maker free",
      "online watermark tool",
      "add logo to image",
      "logo watermark online",
      "transparent watermark maker",
      "watermark images free",
    ],
    canonical: "/add-watermark",
  },

  "rotate-flip-image": {
    title: "Rotate & Flip Image Online – 90°, 180°, 270° Free Tool",
    description: "Rotate images 90, 180, or 270 degrees and flip horizontally or vertically online. Fix sideways photos instantly. Free, no signup required.",
    keywords: [
      "rotate image online",
      "flip image online",
      "image rotator tool",
      "mirror image online",
      "rotate photo free",
      "flip photo horizontally",
      "turn image upside down",
      "fix sideways photo online",
      "rotate image 90 degrees",
      "rotate jpg png",
      "image editing tool online",
      "free image rotator",
    ],
    canonical: "/rotate-flip-image",
  },

  "text-to-speech": {
    title: "Text to Speech Online – Convert Text to Audio & MP3 Free",
    description: "Convert text to audio online free with natural voices. Free text reader and online text to speech converter. Listen online or convert text to voice MP3 instantly.",
    keywords: [
      "text to speech",
      "tts online",
      "text to voice converter",
      "speech generator",
      "text reader online",
      "voice generator free",
      "tts tool free",
      "convert text to audio",
      "read text aloud online",
      "text to mp3 free",
      "online speech tool",
      "ai voice generator",
      "text to audio converter online free",
      "convert text to voice online free",
      "text to speech converter online free",
      "online text to audio converter free",
      "text reader free online",
      "convert text into audio online",
      "text to mp3 converter online free",
      "free online text to audio",
      "speech converter online",
      "txt to speech online",
    ],
    canonical: "/text-to-speech",
  },

  "text-to-slug": {
    title: "Text to Slug Converter – Generate SEO-Friendly URLs Free",
    description: "Convert any text into clean, SEO-friendly URL slugs instantly. Remove special characters, spaces, and uppercase letters automatically. Free tool.",
    keywords: [
      "text to slug",
      "slug generator",
      "url slug converter",
      "seo friendly url",
      "slugify text",
      "convert text to url",
      "slug maker online",
      "clean url generator",
      "wordpress slug generator",
      "blog post slug creator",
      "url optimization tool",
      "seo slug tool",
    ],
    canonical: "/text-to-slug",
  },

  "metatag-generator": {
    title: "Meta Tag Generator – Create SEO Title, OG & Twitter Tags",
    description: "Generate complete SEO meta tags for your website instantly — title, description, keywords, Open Graph, and Twitter Card tags. Free, no signup.",
    keywords: [
      "meta tag generator",
      "seo meta tags generator",
      "html meta tags tool",
      "generate meta description",
      "seo tools online",
      "meta keywords generator",
      "open graph generator",
      "meta title generator",
      "twitter card meta tags",
      "meta tags for seo ranking",
      "website seo tool",
      "meta tags creator",
    ],
    canonical: "/metatag-generator",
  },

  "whatsapp-link-generator": {
    title: "WhatsApp Link Generator – Free Click-to-Chat Link Maker",
    description: "Create a free WhatsApp click-to-chat link (wa.me) with a pre-filled message and downloadable QR code. No signup, no saved contacts needed.",
    keywords: [
      "whatsapp link generator",
      "wa.me link generator",
      "click to chat whatsapp link",
      "whatsapp qr code generator",
      "create whatsapp link free",
      "whatsapp business link generator",
      "whatsapp chat link maker",
      "generate wa.me link",
      "whatsapp link generator online",
      "add whatsapp button to website",
    ],
    canonical: "/whatsapp-link-generator",
  },

  "favicon-generator": {
    title: "Favicon Generator – Create All Favicon Sizes Online Free",
    description: "Generate every favicon size your site needs — 16x16 to 512x512, Apple Touch Icon, and PWA icons — from one image, with ready-to-paste HTML.",
    keywords: [
      "favicon generator",
      "favicon generator online",
      "create favicon from image",
      "favicon maker free",
      "generate ico file online",
      "apple touch icon generator",
      "android chrome icon generator",
      "favicon generator for website",
      "favicon.ico converter",
      "pwa icon generator",
    ],
    canonical: "/favicon-generator",
  },

  "regex-tester": {
    title: "Regex Tester Online – Test Regular Expressions Live Free",
    description: "Test regular expressions online with live match highlighting, capture groups, and flag support. Built-in patterns for email, URL, and phone.",
    keywords: [
      "regex tester",
      "regular expression tester",
      "test regex online",
      "regex validator",
      "javascript regex tester",
      "regex match checker",
      "online regex tool",
      "regex pattern tester",
      "regex checker free",
      "live regex tester",
    ],
    canonical: "/regex-tester",
  },

  "og-preview-checker": {
    title: "Open Graph Preview Checker – Test Social Share Links Free",
    description: "See how your link looks on Facebook, LinkedIn, WhatsApp, and Twitter/X before you share it. Paste your HTML and check for missing OG tags.",
    keywords: [
      "open graph preview checker",
      "og tag checker",
      "facebook link preview tool",
      "twitter card checker",
      "og:image checker",
      "social media preview tool",
      "meta tag checker online",
      "link preview generator",
      "check open graph tags",
      "social share preview tool",
    ],
    canonical: "/og-preview-checker",
  },

};























































// export const seoData = {

//   "qr-generator": {
//     title: "Free QR Code Generator – Create Custom QR Codes Online",
//     description: "Generate QR codes for URLs, text, WiFi, email, and vCard instantly. Download high-quality PNG or SVG. Free, unlimited, no signup required.",
//     keywords: [
//       "qr code generator",
//       "free qr code generator",
//       "create qr code online",
//       "custom qr code maker",
//       "generate qr code free",
//       "qr code maker",
//       "wifi qr code generator",
//       "qr code generator no signup",
//       "online qr code creator",
//       "qr code for url",
//     ],
//     canonical: "/qr-generator",
//   },

//   "password-gen": {
//     title: "Password Generator – Create Strong Secure Passwords Free",
//     description: "Generate strong, secure random passwords instantly. Customize length, symbols, numbers, and uppercase letters. Free, no signup, copy in one click.",
//     keywords: [
//       "password generator",
//       "strong password generator",
//       "secure password maker",
//       "random password generator",
//       "free password generator",
//       "password generator online",
//       "strong password creator",
//       "complex password generator",
//       "password generator no signup",
//       "generate secure password",
//     ],
//     canonical: "/password-gen",
//   },

//   "unit-converter": {
//     title: "Unit Converter – Convert Length, Weight, Temperature Free",
//     description: "Free online unit converter for length, weight, temperature, area, speed, and volume. Fast, accurate conversions instantly. No signup required.",
//     keywords: [
//       "unit converter",
//       "convert units online",
//       "length converter",
//       "weight converter",
//       "temperature converter",
//       "free unit converter",
//       "metric to imperial converter",
//       "kg to lbs converter",
//       "cm to inches converter",
//       "celsius to fahrenheit converter",
//     ],
//     canonical: "/unit-converter",
//   },

//   // CHANGED: removed the "4K" claim (YouTube thumbnails top out at 1280x720) and added the "online" query people actually search
//   "youtube-thumbnail": {
//     title: "YouTube Thumbnail Downloader – Download HD Thumbnails Free",
//     description: "Download YouTube video thumbnails in the highest quality available (up to 1280x720 HD). Paste the video link and save the image. Free, no signup.",
//     keywords: [
//       "youtube thumbnail downloader",
//       "youtube thumbnail downloader online",
//       "download youtube thumbnail",
//       "yt thumbnail download",
//       "youtube thumbnail hd",
//       "youtube thumbnail downloader free",
//       "download youtube video thumbnail",
//       "youtube thumbnail download",
//       "get youtube thumbnail",
//       "youtube thumbnail extractor",
//       "save youtube thumbnail",
//     ],
//     canonical: "/youtube-thumbnail",
//   },

//   // CHANGED: removed the "up to 90%" claim (the homepage says 80%, so the two disagreed)
//   "image-compressor": {
//     title: "Image Compressor – Reduce Image Size Online Free",
//     description: "Compress JPG, PNG, and WebP images online and cut the file size while keeping them sharp. Free, fast, no signup, runs in your browser on mobile and desktop.",
//     keywords: [
//       "image compressor",
//       "compress image online",
//       "reduce image size",
//       "jpg compressor",
//       "png compressor",
//       "compress image without losing quality",
//       "image size reducer",
//       "free image compressor",
//       "compress photo online",
//       "reduce photo size free",
//     ],
//     canonical: "/image-compressor",
//   },

//   "image-to-text": {
//     title: "Image to Text Converter – Extract Text from Image (OCR)",
//     description: "Extract text from images using powerful OCR technology. Supports JPG, PNG, and scanned documents. Free, accurate, no signup required.",
//     keywords: [
//       "image to text",
//       "ocr online",
//       "extract text from image",
//       "photo to text converter",
//       "image to text converter free",
//       "ocr image to text",
//       "picture to text",
//       "scan image to text",
//       "free ocr tool",
//       "convert image to text online",
//     ],
//     canonical: "/image-to-text",
//   },

//   // CHANGED: the old text said "draw, type, or upload" but the tool has no typing mode.
//   // Title/description now target: "free online signature", "convert signature to digital", "signature converter", "scan signature".
//   "signature-maker": {
//     title: "Free Online Signature Maker – Convert Signature to Digital",
//     description: "Create a free online signature: draw it, or upload a photo of your handwritten signature and get a transparent PNG. No signup, no watermark.",
//     keywords: [
//       "free online signature",
//       "online signature maker",
//       "signature maker",
//       "convert signature to digital",
//       "signature converter",
//       "scan signature online free",
//       "digital signature online free",
//       "create digital signature online",
//       "handwritten signature to digital",
//       "transparent signature png",
//       "draw signature online",
//       "signature maker no signup",
//     ],
//     canonical: "/signature-maker",
//   },

//   "heic-to-jpg": {
//     title: "HEIC to JPG Converter – Convert iPhone Photos Free Online",
//     description: "Convert iPhone HEIC photos to JPG instantly. Free, unlimited batch conversion, no signup, no watermark. Works on Windows, Android & any browser.",
//     keywords: [
//       "heic to jpg",
//       "convert heic to jpg",
//       "heic to jpg free",
//       "iphone heic to jpg",
//       "heic converter online",
//       "convert heic to jpg online free",
//       "heic to jpg unlimited",
//       "free heic converter",
//       "heic to jpeg",
//       "convert iphone photos to jpg",
//     ],
//     canonical: "/heic-to-jpg",
//   },

//   "text-to-pdf": {
//     title: "Text to PDF Converter – Convert TXT to PDF Online Free",
//     description: "Convert plain text files into formatted PDF documents instantly. Customize font, margins, and layout. Free, no signup, download instantly.",
//     keywords: [
//       "text to pdf",
//       "txt to pdf converter",
//       "convert text to pdf",
//       "text file to pdf",
//       "text to pdf free",
//       "online text to pdf converter",
//       "notepad to pdf",
//       "plain text to pdf",
//       "txt to pdf online free",
//       "convert txt file to pdf",
//     ],
//     canonical: "/text-to-pdf",
//   },

//   "image-converter": {
//     title: "Image Converter – Convert JPG, PNG, WebP Online Free",
//     description: "Convert images between JPG, PNG, WebP, and other formats instantly. High quality output, free, no signup, batch conversion supported.",
//     keywords: [
//       "image converter",
//       "jpg to png",
//       "png to jpg",
//       "webp converter",
//       "convert image format",
//       "free image converter",
//       "image format converter online",
//       "jpg to webp converter",
//       "png to webp",
//       "convert image online free",
//     ],
//     canonical: "/image-converter",
//   },

//   "image-resizer": {
//     title: "Image Resizer – Resize Images Online by Pixels Free",
//     description: "Resize images online by pixels, width, or height. Supports JPG, PNG, and WebP. Free, fast, no signup, no quality loss. Works on mobile and desktop.",
//     keywords: [
//       "image resizer",
//       "resize image online",
//       "photo resizer",
//       "change image size",
//       "resize jpg png",
//       "image resizer free",
//       "resize image without losing quality",
//       "resize photo online free",
//       "image size changer",
//       "resize image to specific size",
//     ],
//     canonical: "/image-resizer",
//   },

//   // CHANGED: targets "crop image online", "photo cropper", "crop picture online" and the exact size/ratio feature shown on the homepage.
//   // After you add ratio presets (1:1, 16:9, Instagram), mention them here.
//   "image-cropper": {
//     title: "Crop Image Online Free – Image & Photo Cropper",
//     description: "Crop images and photos online for free. Crop JPG, PNG, or WebP to an exact size or aspect ratio and download instantly. No signup, runs in your browser.",
//     keywords: [
//       "image cropper",
//       "crop image online",
//       "online image cropper",
//       "photo cropper",
//       "crop picture online",
//       "crop photo online free",
//       "image crop online",
//       "free image cropper",
//       "crop jpg png",
//       "crop image without watermark",
//     ],
//     canonical: "/image-cropper",
//   },

//   "word-counter": {
//     title: "Word Counter Online – Count Words, Characters & Sentences",
//     description: "Count words, characters, sentences, and paragraphs instantly with our free online word counter tool. Fast, accurate, and no signup required.",
//     keywords: [
//       "word counter",
//       "character counter",
//       "online word count tool",
//       "count words online",
//       "text counter tool",
//       "word and character counter",
//       "free word counter tool",
//       "sentence counter",
//       "paragraph counter",
//       "online text analyzer",
//     ],
//     canonical: "/word-counter",
//   },

//   "case-converter": {
//     title: "Case Converter – Uppercase, Lowercase & Title Case Tool",
//     description: "Convert text to uppercase, lowercase, sentence case, or title case instantly. Free online case converter with one-click formatting.",
//     keywords: [
//       "case converter",
//       "uppercase to lowercase",
//       "lowercase to uppercase",
//       "text case converter",
//       "title case converter",
//       "sentence case tool",
//       "change text case online",
//       "capitalize text tool",
//       "free case converter",
//       "text formatting tool",
//     ],
//     canonical: "/case-converter",
//   },

//   "base64-tool": {
//     title: "Base64 Encoder & Decoder – Encode/Decode Online Free",
//     description: "Encode and decode Base64 strings instantly with our free online tool. Supports text, images, and files. Fast, accurate, and secure.",
//     keywords: [
//       "base64 encoder",
//       "base64 decoder",
//       "encode base64 online",
//       "decode base64 string",
//       "base64 converter tool",
//       "base64 encode decode",
//       "online base64 tool",
//       "base64 image converter",
//       "free base64 encoder",
//       "base64 string decoder",
//     ],
//     canonical: "/base64-tool",
//   },

//   "json-formatter": {
//     title: "JSON Formatter & Validator – Beautify JSON Online Free",
//     description: "Format, beautify, and validate JSON data instantly with our free JSON formatter tool. Fix errors and improve readability easily.",
//     keywords: [
//       "json formatter",
//       "json beautifier",
//       "json validator",
//       "format json online",
//       "pretty json tool",
//       "json parser",
//       "fix json errors",
//       "online json viewer",
//       "json editor tool",
//       "free json formatter",
//     ],
//     canonical: "/json-formatter",
//   },

//   "lorem-ipsum": {
//     title: "Lorem Ipsum Generator – Generate Dummy Text Online Free",
//     description: "Generate Lorem Ipsum placeholder text instantly. Create paragraphs, sentences, or words for design and development projects.",
//     keywords: [
//       "lorem ipsum generator",
//       "dummy text generator",
//       "placeholder text generator",
//       "lorem ipsum text",
//       "generate lorem ipsum",
//       "random text generator",
//       "dummy content generator",
//       "lorem ipsum paragraphs",
//       "free lorem ipsum generator",
//       "text filler generator",
//     ],
//     canonical: "/lorem-ipsum",
//   },

//   // CHANGED: adds the "hex code finder" and "rgb color picker" queries seen in Search Console.
//   // The tool currently shows HEX, RGB, HSL. Once you add HSB, use this title instead:
//   //   title: "Color Picker Online – HEX, RGB, HSB & HSL Code Finder",
//   // and add "hsb color picker" to the keywords.
//   "color-picker": {
//     title: "Color Picker Online – HEX, RGB & HSL Color Code Finder",
//     description: "Free online color picker and hex code finder. Pick any color and get its HEX, RGB, and HSL codes instantly. Made for designers and developers, no signup.",
//     keywords: [
//       "color picker",
//       "hex color picker",
//       "rgb color picker",
//       "hsl color picker",
//       "hex code finder",
//       "color hex finder",
//       "color code generator",
//       "pick color online",
//       "online color picker",
//       "color palette tool",
//     ],
//     canonical: "/color-picker",
//   },

//   "add-watermark": {
//     title: "Add Watermark to Image – Text & Logo Watermark Free",
//     description: "Add text or logo watermark to any image online for free. Control position, opacity, size, and rotation. No signup, 100% browser-based.",
//     keywords: [
//       "add watermark to image",
//       "watermark tool online",
//       "image watermark generator",
//       "add text watermark",
//       "photo watermark online",
//       "protect images watermark",
//       "watermark maker free",
//       "online watermark tool",
//       "add logo to image",
//       "logo watermark online",
//       "transparent watermark maker",
//       "watermark images free",
//     ],
//     canonical: "/add-watermark",
//   },

//   "rotate-flip-image": {
//     title: "Rotate & Flip Image Online – 90°, 180°, 270° Free Tool",
//     description: "Rotate images 90, 180, or 270 degrees and flip horizontally or vertically online. Fix sideways photos instantly. Free, no signup required.",
//     keywords: [
//       "rotate image online",
//       "flip image online",
//       "image rotator tool",
//       "mirror image online",
//       "rotate photo free",
//       "flip photo horizontally",
//       "turn image upside down",
//       "fix sideways photo online",
//       "rotate image 90 degrees",
//       "rotate jpg png",
//       "image editing tool online",
//       "free image rotator",
//     ],
//     canonical: "/rotate-flip-image",
//   },

//   "text-to-speech": {
//     title: "Text to Speech Online – Convert Text to Audio Free",
//     description: "Convert any text to natural-sounding speech online for free. Supports multiple voices and languages. Listen or download audio instantly.",
//     keywords: [
//       "text to speech",
//       "tts online",
//       "text to voice converter",
//       "speech generator",
//       "text reader online",
//       "voice generator free",
//       "tts tool free",
//       "convert text to audio",
//       "read text aloud online",
//       "text to mp3 free",
//       "online speech tool",
//       "ai voice generator",
//     ],
//     canonical: "/text-to-speech",
//   },

//   "text-to-slug": {
//     title: "Text to Slug Converter – Generate SEO-Friendly URLs Free",
//     description: "Convert any text into clean, SEO-friendly URL slugs instantly. Remove special characters, spaces, and uppercase letters automatically. Free tool.",
//     keywords: [
//       "text to slug",
//       "slug generator",
//       "url slug converter",
//       "seo friendly url",
//       "slugify text",
//       "convert text to url",
//       "slug maker online",
//       "clean url generator",
//       "wordpress slug generator",
//       "blog post slug creator",
//       "url optimization tool",
//       "seo slug tool",
//     ],
//     canonical: "/text-to-slug",
//   },

//   "metatag-generator": {
//     title: "Meta Tag Generator – Create SEO Title, OG & Twitter Tags",
//     description: "Generate complete SEO meta tags for your website instantly — title, description, keywords, Open Graph, and Twitter Card tags. Free, no signup.",
//     keywords: [
//       "meta tag generator",
//       "seo meta tags generator",
//       "html meta tags tool",
//       "generate meta description",
//       "seo tools online",
//       "meta keywords generator",
//       "open graph generator",
//       "meta title generator",
//       "twitter card meta tags",
//       "meta tags for seo ranking",
//       "website seo tool",
//       "meta tags creator",
//     ],
//     canonical: "/metatag-generator",
//   },

//   "whatsapp-link-generator": {
//     title: "WhatsApp Link Generator – Free Click-to-Chat Link Maker",
//     description: "Create a free WhatsApp click-to-chat link (wa.me) with a pre-filled message and downloadable QR code. No signup, no saved contacts needed.",
//     keywords: [
//       "whatsapp link generator",
//       "wa.me link generator",
//       "click to chat whatsapp link",
//       "whatsapp qr code generator",
//       "create whatsapp link free",
//       "whatsapp business link generator",
//       "whatsapp chat link maker",
//       "generate wa.me link",
//       "whatsapp link generator online",
//       "add whatsapp button to website",
//     ],
//     canonical: "/whatsapp-link-generator",
//   },

//   "favicon-generator": {
//     title: "Favicon Generator – Create All Favicon Sizes Online Free",
//     description: "Generate every favicon size your site needs — 16x16 to 512x512, Apple Touch Icon, and PWA icons — from one image, with ready-to-paste HTML.",
//     keywords: [
//       "favicon generator",
//       "favicon generator online",
//       "create favicon from image",
//       "favicon maker free",
//       "generate ico file online",
//       "apple touch icon generator",
//       "android chrome icon generator",
//       "favicon generator for website",
//       "favicon.ico converter",
//       "pwa icon generator",
//     ],
//     canonical: "/favicon-generator",
//   },

//   "regex-tester": {
//     title: "Regex Tester Online – Test Regular Expressions Live Free",
//     description: "Test regular expressions online with live match highlighting, capture groups, and flag support. Built-in patterns for email, URL, and phone.",
//     keywords: [
//       "regex tester",
//       "regular expression tester",
//       "test regex online",
//       "regex validator",
//       "javascript regex tester",
//       "regex match checker",
//       "online regex tool",
//       "regex pattern tester",
//       "regex checker free",
//       "live regex tester",
//     ],
//     canonical: "/regex-tester",
//   },

//   "og-preview-checker": {
//     title: "Open Graph Preview Checker – Test Social Share Links Free",
//     description: "See how your link looks on Facebook, LinkedIn, WhatsApp, and Twitter/X before you share it. Paste your HTML and check for missing OG tags.",
//     keywords: [
//       "open graph preview checker",
//       "og tag checker",
//       "facebook link preview tool",
//       "twitter card checker",
//       "og:image checker",
//       "social media preview tool",
//       "meta tag checker online",
//       "link preview generator",
//       "check open graph tags",
//       "social share preview tool",
//     ],
//     canonical: "/og-preview-checker",
//   },

// };


